#!/usr/bin/with-contenv sh

if [ -n "${NO_SERVER}" ];then
  echo "
INFO: Skipping nginx init because NO_SERVER environment variable is set.
"
  s6-svc -d /var/run/s6/services/nginx
  exit 0
fi

exec /usr/sbin/nginx -c /config/nginx.conf
